language: python
python:
  - "3.6" # current default Python on Travis CI
  - "3.7"
  - "3.8"

env:
  - SQLITE=True SHYNET_ADMIN_EMAIL=admin@admin.com

# install pipenv before installing dependencies.
before_install:
  - pip3 install pipenv

# command to install dependencies
install:
  - pip3 install coveralls
  - pipenv install

before_script:
  - cd shynet/
  - ./manage.py migrate
  - ./manage.py collectstatic

# command to run tests
script:
  - coverage run --source=. manage.py test

after_success:
  - coveralls
